'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18034
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices
<Assembly: AssemblyTitle("DNNStuff.ModuleRotator"),  _
 Assembly: AssemblyDescription("DNNStuff.ModuleRotator - DNN6 Install - .NET 3.5"),  _
 Assembly: AssemblyCompany("DNNStuff"),  _
 Assembly: AssemblyProduct("DNNStuff ModuleRotator"),  _
 Assembly: AssemblyCopyright("Copyright (c) DNNStuff 2004-2012"),  _
 Assembly: ComVisible(false),  _
 Assembly: CLSCompliant(true),  _
 Assembly: AssemblyVersion("04.02.00"),  _
 Assembly: AssemblyFileVersion("04.02.00")> 

