'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DNNStuff.ModuleRotator

    Partial Public Class EditModuleRotator

        '''<summary>
        '''lblTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTabs As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cmdAddModule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddModule As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''grdModules control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdModules As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''lblAutoHide control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAutoHide As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkHideTitles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideTitles As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblTimerEnabled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTimerEnabled As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkTimerEnabled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkTimerEnabled As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblTimerDelay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTimerDelay As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTimerDelay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTimerDelay As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valTimerDelayInteger control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valTimerDelayInteger As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''valTimerDelayGreaterThanEqualToZero control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valTimerDelayGreaterThanEqualToZero As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''lblHoverEnabled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHoverEnabled As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkHoverEnabled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHoverEnabled As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
